### PR TITLE
Forecast attribute fixes

### PR DESCRIPTION
**Pull request by 696GrocuttT**
The forecast attributes had a few bugs that this patch fixes:

- The cross over between estimated actuals and forecasts could result in duplicate samples
- The timestamps were labeled as "period_end" when they were actually for the start of the period
- The attributes only contained data in 1 hour chunks. Since UK electricity prices change every 30 minutes exposing the resolution available is useful.

### CODE REVIEW

**Comment by oziee** [comment]
thanks.. someone might like to use this but it doesn't fit in with the forecast integration use

> The cross over between estimated actuals and forecasts could result in duplicate samples

never seen anything happen, but if you can show what you are seeing then..

>The attributes only contained data in 1 hour chunks. Since UK electricity prices change every 30 minutes exposing the resolution available is useful.

HA only works in 1hr blocks, not 30min blocks. "prices" changing in 30min blocks has nothing to do with forecasting solar production

caching solcast site calls is great if your never going to change solcast site info after you install the integration. But if anyone ever alters the site settings in solcast then it would never change in HA

**Comment by 696GrocuttT** [comment]
The attached picture shows the problem with the duplicate samples circled in red. 
solcast data2

HA doesn't only work in 1 hour blocks, for example an automation can fire at any point, not just on the hour. The 1 hour block is just the granularity of the display in the energy dashboard, it doesn't limit any other uses of the forecast data. In my case I'm combining the solar forecast with the 30 minute pricing data to estimate the value of the solar power generated. This then is used to determine when to charge and discharge a battery to get the maximum benefit. Before this patch the solar forecast was grouped together into 1 hour blocks, that I then had to split apart again to match the pricing data I have. In the process this looses a lot of accuracy. Moving to 30 minute blocks doesn't really have any down sides. The original 1 hour blocks are still available in the "forecast" attribute key, but the original 30 minutes slots from solcast are also available in the detailedForecast attribute for people like me that need the additional precision.

Lastly, you asked about the caching. If you look at the code you'll see that this is only when testing the code. So the caching won't cause any problems when altering site settings etc. It just means that if you're testing changes to the code (via the new test.py wrapper) you don't burn through all the API calls you're allowed for the day.

**Comment by oziee** [comment]
that double shouldn't matter.. it goes into a dict so there aren't be two keys with the same key name which is the date.time

**Comment by 696GrocuttT** [comment]
Thanks for merging this.
Just FYI: The double values do matter as they affect the total forecast for the day (via get_total_kwh_forecast_today()). In my case they were also causing more serious problems with automations / appdaemon code that was using the attribute instead of just using the summary entities you generate.

**Comment by oziee** [comment]
something is wrong with the code now.. im going to have to investigate, but its not working.. it used to work :)
Screen Shot 2022-10-30 at 11 07 30 am

my setup in solcast can not produce that much power

**Comment by 696GrocuttT** [comment]
Hmm, that's a bit odd. I haven't noticed anything like that on my setup, but its winter here and my solar production is so low at the moment something like this could be easily mistaken for normal inaccuracies in the forecasts. From the look of the graph you showed the forecast is probably ok and its just the estimated actuals that are wrong. I've had a look through the code and can't see anything that would cause this. I'll keep looking my side to see if I can spot anything.

On an unrelated note, I found another bug whereby an unhandled exception could leave the self._data as a list instead of a dict. This then causes all subsequent forecast updates to fail. I've got a fix for this already (see link below) but I want to test it for a day or so before submitting a pull request.
https://github.com/oziee/ha-solcast-solar/compare/v3...696GrocuttT:ha-solcast-solar:v3

**Comment by oziee** [comment]
One account with two rooftop sites

**Comment by galtaforce** [comment]
Hi team. I'm not sure where I should be putting this but as of updating to HA 2022.11.0. Version v3.0.23 of ha-solcast-solar, the device is no longer selectable for forecasting in the energy dashboard. Excuse my inablility to use github properly! The device and entities all appear to be working fine otherwise.

 
Screenshot 2022-11-03 170315
Screenshot 2022-11-03 170342

**Pull request merged**
